x-services-templates:
  # RDMA requires root, cannot specify a user
  vllm-template: &vllm-template
    image: vllm-node-tf5
    container_name: vllm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    mem_limit: 110g
    memswap_limit: 120g
    pids_limit: 4096
    network_mode: host
    shm_size: 64g
    devices:
      - /dev/infiniband:/dev/infiniband
    volumes:
      - /sys/class/infiniband:/sys/class/infiniband:ro
      # used for clearing buffers to maximize available memory
      - /proc/sys/vm/drop_caches:/host/proc/sys/vm/drop_caches
      # configure, or omit this, per your needs
      # use a directory like this if you have models already downloaded to a specific location
      - ${MODELS_BASEDIR}:/models

      # use this bind mount if you use hf to download and cache models for you
      #- $HOME/.cache/huggingface:/root/.cache/huggingface

      - ./ray-start-head.sh:/opt/nvidia/entrypoint.d/98-ray-start-head.sh:ro
      - ./drop-caches.sh:/opt/nvidia/entrypoint.d/99-drop-caches.sh:ro
      - ./setup-ssh.sh:/opt/nvidia/entrypoint.d/90-setup-ssh.sh:ro
      - ./launch-cluster.sh:/launch-cluster.sh:ro

      # persist generated caches, can also use to persist hf downloaded models, add an entry as necessary
      - cache-data:/root/.cache/vllm
      - cache-data:/root/.triton
      - cache-data:/root/.cache/flashinfer

      # setup passwordless ssh into worker nodes
      - $HOME/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - $HOME/.ssh/id_ed25519_shared:/root/.ssh/id_ed25519_shared:ro
      - $HOME/.ssh/config:/root/.ssh/host_config:ro
    cap_add:
      - IPC_LOCK
      - SYS_RESOURCE
    environment:
      # space separate listed of worker nodes
      - WORKER_NODES=node2
      - RAY_NODE_IP_ADDRESS=${NODE_IP_ADDRESS}
      - RAY_OVERRIDE_NODE_IP_ADDRESS=${NODE_IP_ADDRESS}
      #- RAY_CLUSTER_SIZE=${RAY_CLUSTER_SIZE}
      # disable ray, use --nnodes in VLLM by default
      - RAY_CLUSTER_SIZE=0
      - RAY_memory_monitor_refresh_ms=0
      - RAY_num_prestart_python_workers=0
      - RAY_object_store_memory=1073741824
      - VLLM_HOST_IP=${NODE_IP_ADDRESS}
      # int4-AutoAround kernel
      - VLLM_MARLIN_USE_ATOMIC_ADD=1
      - MN_IF_NAME=enp1s0f1np1 
      - UCX_NET_DEVICES=enp1s0f1np1
      - NCCL_IB_DISABLE=0
      - NCCL_SOCKET_IFNAME=enp1s0f1np1 
      - NCCL_IB_HCA=rocep1s0f1,roceP2p1s0f1
      - GLOO_SOCKET_IFNAME=enp1s0f1np1
      - OMPI_MCA_btl_tcp_if_include=enp1s0f1np1
      - TP_SOCKET_IFNAME=enp1s0f1np1
      - NCCL_IGNORE_CPU_AFFINITY=1 
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      #- NCCL_DEBUG=INFO
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

services:
  vllm-397b:
    <<: *vllm-template
    profiles: ["ignore"]
    command: >
      vllm serve
        /models/Qwen3.5-397B-A17B-int4-AutoRound
        --served-model-name "Qwen3.5 397B:int4"
        --max-model-len 32768
        --max-num-seqs 4
        --enable-prefix-caching
        --gpu-memory-utilization 0.9209
        --port 8000
        --host 0.0.0.0
        --load-format safetensors
        --kv-cache-dtype fp8_e4m3
        --dtype auto
        --enable-chunked-prefil
        --enable-auto-tool-choice
        --tool-call-parser qwen3_coder
        --reasoning-parser qwen3
        --max-num-batched-tokens 16384
        --trust-remote-code
        --mm-encoder-tp-mode data
        --distributed-executor-backend ray
        --tensor-parallel-size 2

  vllm-122b:
    <<: *vllm-template
    command: >
      vllm serve
        /models/Qwen3.5-122B-A10B-FP8
        --served-model-name "Qwen3.5 122B:FP8"
        --max-model-len 262144
        --max-num-seqs 4
        --enable-prefix-caching
        --gpu-memory-utilization 0.6
        --port 8000
        --host 0.0.0.0
        --load-format fastsafetensors
        --kv-cache-dtype fp8_e4m3
        --enable-chunked-prefil
        --enable-auto-tool-choice
        --tool-call-parser qwen3_coder
        --reasoning-parser qwen3
        --max-num-batched-tokens 8192
        --trust-remote-code
        --mm-encoder-tp-mode data
        --distributed-executor-backend ray
        --tensor-parallel-size 2
        -O3

  vllm-noray-minimax:
    <<: *vllm-template
    command: >
      vllm serve
        /models/MiniMax-M2.7
        --served-model-name "MiniMax-M2.7:FP8"
        --max-model-len 196608
        --max-num-seqs 4
        --enable-prefix-caching
        --gpu-memory-utilization 0.700
        --port 8000
        --host 0.0.0.0
        --load-format fastsafetensors
        --kv-cache-dtype fp8_e4m3
        --enable-chunked-prefil
        --enable-auto-tool-choice
        --tool-call-parser qwen3_coder
        --reasoning-parser qwen3
        --max-num-batched-tokens 8192
        --trust-remote-code
        --tensor-parallel-size 2
        --nnodes 2 --node-rank 0 --master-addr node1 --master-port 54321
        -O3

  vllm-35b:
    <<: *vllm-template
    command: >
      vllm serve
        /models/Qwen3.6-35B-A3B-FP8
        --served-model-name "Qwen3.5 35B:FP8"
        --max-model-len 262144
        --max-num-seqs 4
        --enable-prefix-caching
        --gpu-memory-utilization 0.6
        --port 8000
        --host 0.0.0.0
        --load-format fastsafetensors
        --kv-cache-dtype fp8_e4m3
        --enable-chunked-prefil
        --enable-auto-tool-choice
        --tool-call-parser qwen3_coder
        --reasoning-parser qwen3
        --max-num-batched-tokens 8192
        --trust-remote-code
        --mm-encoder-tp-mode data
        -O3

  vllm-noray:
    <<: *vllm-template
    command: >
      /launch-cluster.sh vllm serve
        /models/Qwen3.5-397B-A17B-int4-AutoRound
        --served-model-name "Qwen3.5 397B:int4"
        --max-model-len 262144
        --max-num-seqs 4
        --enable-prefix-caching
        --gpu-memory-utilization 0.909
        --port 8000
        --host 0.0.0.0
        --load-format safetensors
        --kv-cache-dtype fp8_e4m3
        --dtype auto
        --enable-chunked-prefil
        --enable-auto-tool-choice
        --tool-call-parser qwen3_coder
        --reasoning-parser qwen3
        --max-num-batched-tokens 16384
        --trust-remote-code
        --mm-encoder-tp-mode data
        --tensor-parallel-size 2
        --nnodes 2 --node-rank 0 --master-addr node1 --master-port 54321

#--speculative-config '{"method":"qwen3_next_mtp","num_speculative_tokens":2}'
  vllm-gemma:
    <<: *vllm-template
    profiles: ["ignore"]
    command: >
      vllm serve
        /models/gemma-4-31B-it-NVFP4
        --served-model-name gemma-4-31B-it
        --max-model-len 262144
        --enable-prefix-caching
        --gpu-memory-utilization 0.6
        --port 8000
        --host 0.0.0.0
        --load-format fastsafetensors
        --kv-cache-dtype fp8_e4m3
        --enable-chunked-prefil
        --max-num-batched-tokens 8192
        --trust-remote-code
        --mm-encoder-tp-mode data
        --distributed-executor-backend ray
        --tensor-parallel-size 2
        -O3

volumes:
  cache-data:
